# Jekyll Configuration for GitHub Pages

# Site settings
title: Grobb Wiki
description: A guide to the world, NPCs, locations, and lore
url: "" # Leave empty for GitHub Pages
repository: griffinsharkey/grobb_wiki # github-metadata
favicon: favicon.ico

# Default settings
defaults:
  - scope:
      path: "docs"
      type: "pages"
    
    values:
      layout: "default"

plugins:
    - jekyll-relative-links

relative_links:
  enabled: true
  collections: false

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Search settings
search_enabled: true
search.button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Exclude files from build
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md

